import "./globals.css";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import fonts from "@/fonts/fonts";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fonts.className, 'font-sans')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="py-4 px-12 w-full bg-white dark:bg-neutral-950 ">
            <Navbar />
            {children}

          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
